version: 2.1

parameters:
  setup:
    type: boolean
    default: true
  main_workflow:
    type: boolean
    default: false
  beta_workflow:
    type: boolean
    default: false
  feature_branch_workflow:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.1.0

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: ./scripts/ci-setup.sh
  lint:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  publish:
    docker:
      - image: cimg/node:18.13.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  setup:
    when: << pipeline.parameters.setup >>
    jobs:
      - setup:
          context:
            - Semantic Release
  feature_branch:
    when: << pipeline.parameters.feature_branch_workflow >>
    jobs:
      - lint
      - node/test:
          matrix:
            parameters:
              version:
                - "18.13.0"
                - "16.19.0"
  main:
    when: << pipeline.parameters.main_workflow >>
    jobs:
      - lint
      - node/test:
          matrix:
            parameters:
              version:
                - "18.13.0"
                - "16.19.0"
      - publish:
          context:
            - Semantic Release
          requires:
            - lint
            - node/test

  beta:
    when: << pipeline.parameters.beta_workflow >>
    jobs:
      - lint
      - node/test:
          matrix:
            parameters:
              version:
                - "18.13.0"
                - "16.19.0"
      - publish:
          context:
            - Semantic Release
          requires:
            - lint
            - node/test